# Variables that contains the user credentials to access Twitter API
ACCESS_TOKEN ='XXXXXXXXXXXXXXXXXXXXX'
ACCESS_TOKEN_SECRET ='XXXXXXXXXXXXXXXXXXXXXXX'
CONSUMER_KEY = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
CONSUMER_SECRET = 'XXXXXXXXXXXXXXXXXXXX'
